In [1]:
import pandas as pd
import numpy as np
import os
import zipfile
from PyPDF2 import PdfFileReader
from pathlib import Path

In [10]:
df = pd.read_csv(
         'dados/TODOS_sem_arquivos_separados.csv',
         dtype=str,
    )
# arq_zip = pd.read_csv(
#         'dados/arquivos_zip.csv',
#         dtype=str,
# )

In [2]:
tudao = pd.read_csv(
     'dados/DADOS_CRUZADOS.csv',
     dtype=str,
)

In [5]:
df['Extensão do Arquivo'].unique()

array([nan, 'pdf', 'zip', 'docx', 'mp4', 'mp3', 'DOCX'], dtype=object)

In [12]:
df['Nome do Arquivo'].unique()

array([nan, 'Plano_de_desenvolvimento_6o_ano_SESI_bimestre_1_OK_FNDE.pdf',
       'Plano_de_desenvolvimento_6o_ano_bimestre_1_OK-corrigido_FNDE.pdf',
       ..., 'COL1TITULO4_MP_4_MATEMATICA_DM_CORRIGIDO_FNDE.pdf',
       'COL1TITULO5_MP_5_MATEMATICA_DM_CORRIGIDO_FNDE.pdf',
       'COL1TITULO1_LP_4A5_PRE_ESCOLA_DM_FNDE.pdf'], dtype=object)

In [ ]:
df.to_csv('dados/TODOS.csv', index = False)

In [54]:
ren = arq_zip.rename(columns={'red_id': 'id', 'nome': 'Nome do Arquivo', 'tamanho': 'Size',
                       'tamanho zipado': 'Zipped size', 'extensão': 'Extensão do Arquivo',
                       'path': 'Caminho Local'})
ren = ren[ren['Extensão do Arquivo'] != 'DS_Store']
ren['Extensão do Arquivo'].unique()

array(['docx', 'mp4', 'mp3', 'pdf', 'DOCX'], dtype=object)

In [ ]:
df.loc[df['Extensão do Arquivo no Header'] == 'text/html; charset=ISO-8859-1']

In [46]:
df.columns

Index(['row', 'id', 'Edital', 'CNPJ Editora', 'Editora', 'Código Coleção',
       'Coleção', 'Código Volume', 'Volume', 'Componente', 'Série', 'Formato',
       'Exemplar', 'Tipo de Arquivo', 'Arquivo', 'Header', 'Header get()',
       'Nome do Arquivo', 'Extensão do Arquivo', 'Deve ser baixado', 'Baixado',
       'Caminho Local', 'Extensão do Arquivo no Header', 'Integridade', 'Size',
       'Zipped size'],
      dtype='object')

In [68]:
ren.columns

Index(['id', 'Nome do Arquivo', 'Size', 'Zipped size', 'Extensão do Arquivo',
       'Caminho Local'],
      dtype='object')

In [ ]:
# for index, row in df.iterrows():
#     if (row['Extensão do Arquivo'] in ['zip', 'x-zip-compressed']):
#         #print('rowz')
#         rows_zip = ren[ren['id'] == row['id']]
#         #print(rows_zip)
#         i = 1
#         for i_zip, r_zip in rows_zip.iterrows():
#             alter_dataframe_register(i_zip, row, r_zip, i)
#             i += 1

# def alter_dataframe_register(index, origin_row, destiny_row, i):
#     ren.at[index, 'Edital'] = origin_row['Edital']
#     ren.at[index, 'CNPJ Editora'] = origin_row['CNPJ Editora']
#     ren.at[index, 'Editora'] = origin_row['Editora']
#     ren.at[index, 'Código Coleção'] = origin_row['Código Coleção']
#     ren.at[index, 'Coleção'] = origin_row['Coleção']
#     ren.at[index, 'Código Volume'] = origin_row['Código Volume']
#     ren.at[index, 'Volume'] = origin_row['Volume']
#     ren.at[index, 'Componente'] = origin_row['Componente']
#     ren.at[index, 'Série'] = origin_row['Série']
#     ren.at[index, 'Formato'] = origin_row['Formato']
#     ren.at[index, 'Exemplar'] = origin_row['Exemplar']
#     ren.at[index, 'Tipo de Arquivo'] = origin_row['Tipo de Arquivo']
#     ren.at[index, 'Arquivo'] = origin_row['Arquivo']
#     ren.at[index, 'Header'] = origin_row['Header']
#     #ren.at[index, 'Header get()'] = origin_row['Header get()']
#     ren.at[index, 'Deve ser baixado'] = origin_row['Deve ser baixado']
#     ren.at[index, 'Baixado'] = origin_row['Baixado']
#     #ren.at[index, 'Extensão do Arquivo no Header'] = origin_row['Extensão do Arquivo no Header']
#     ren.at[index, 'Integridade'] = origin_row['Integridade']
#     ren.at[index, 'id_zip'] = i
#     print(ren.at[index, 'Edital'])

In [ ]:
# df_sem_zip = ren[ren['Extensão do Arquivo'] != 'DS_Store']

In [90]:
# m = m[(m['Extensão do Arquivo'] != 'zip') & (m['Extensão do Arquivo'] != 'x-zip-compressed')]

In [91]:
# m['Extensão do Arquivo'].unique()

array([nan, 'pdf', 'docx', 'mp4', 'mp3', 'DOCX'], dtype=object)

In [19]:
#ren = ren[ren['Extensão do Arquivo'] != 'DS_Store']
#m.loc[m['Extensão do Arquivo'] == 'DS_Store']

# ren['Extensão do Arquivo'].unique()

array(['docx', 'mp4', 'mp3', 'pdf', 'DOCX'], dtype=object)

In [84]:
# ren.to_csv('dados/DADOS_ZIP.csv', index = False)

In [92]:
# m.to_csv('dados/DADOS_CRUZADOS.csv', index = False)

In [3]:
# def badly_zip_check (path, df, index):
#     for root, dirs, files in os.walk(path):
#         for file in files:
#             if file.endswith('.zip'):
#                 try:
#                     zfile = zipfile.ZipFile(path + '/' + file)
#                 except zipfile.BadZipfile as ex:
#                     print (df.at[index, 'id'] + " no a zip file: " + ex)
#                     df.at[index, 'Integridade'] = 'no a zip file'
#                     continue

#                 ret = zfile.testzip()

#                 if ret is not None:
#                     print (df.at[index, 'id'] + " bad zip file, error: " + ret)
#                     df.at[index, 'Integridade'] = 'bad zip file'
#                 else:
#                     print (df.at[index, 'id'] + " OK")
#                     df.at[index, 'Integridade'] = 'ok'
                
#                 df.to_csv('dados/TODOS.csv', index = False)

In [19]:
# def unzip_all (df):
#     for index, row in df.iterrows():
#         if(row['Extensão do Arquivo'] in ['zip', 'x-zip-compressed']):
# #             print (row['id'] + ' - ' + row['Edital'])
# #             row['Nome do Arquivo']
#             path = 'arquivos/' + row['Edital'] + '/zip/' + row['id']
# #             path = row['id']
            
#             with zipfile.ZipFile(path + '/' + row['Nome do Arquivo'], "r") as zip_ref:
#                 zip_ref.extractall(path)
#             os.remove(path + '/' + row['Nome do Arquivo'])
            
#             df.at[index, 'Unzip'] = 'ok'

# # unzip_all(df)

In [22]:
# def verify_no_unzip (df):
#     print('hahaha')
#     for index, row in df.iterrows():
#         if(row['Extensão do Arquivo'] in ['zip', 'x-zip-compressed'] and row['Unzip'] != 'ok'):
#             print(row['id'])
# verify_no_unzip(df)

hahaha


In [34]:
# each_dataframe(df)

arquivos/PNLD 2020 - Obras Didáticas - Anos Finais do Ensino Fundamental/3974
3974 OK
arquivos/PNLD 2020 - Obras Didáticas - Anos Finais do Ensino Fundamental/3990
3990 OK
arquivos/PNLD 2020 - Obras Didáticas - Anos Finais do Ensino Fundamental/4670
4670 OK


In [19]:
# for index, row in df.iterrows():
#     if (row['Integridade'] != 'ok') and (row['Extensão do Arquivo'] in ['zip', 'x-zip-compressed']):
#         path = 'arquivos/' + row['Edital'] + '/' + row['id']
#         print (path + row['Integridade'])
#         df.at[index, 'Baixado'] = 'Não'
#         df.to_csv('dados/TODOS.csv', index = False)
        

arquivos/PNLD 2020 - Obras Didáticas - Anos Finais do Ensino Fundamental/3067no a zip file
arquivos/PNLD 2020 - Obras Didáticas - Anos Finais do Ensino Fundamental/3974no a zip file
arquivos/PNLD 2020 - Obras Didáticas - Anos Finais do Ensino Fundamental/3990no a zip file
arquivos/PNLD 2020 - Obras Didáticas - Anos Finais do Ensino Fundamental/4670no a zip file


In [23]:
# def get_all_file_sizes (df):
#     for index, row in df.iterrows():
#         if row['Baixado'] == 'Sim':
#             path = 'arquivos/' + row['Edital'] + '/' + row['id']
#             print(path);
#             get_size_file_in_kb(path, df, index)


# def get_size_file_in_kb(path, df, index):
#     for root, dirs, files in os.walk(path):
#         for file in files:
#             if file.endswith('.zip'):
#                 get_real_and_zipped_size_in_kb(path, df, index, file)
#             else:
#                 get_size_file_in_kb(path, df, index, file)

# def get_size_file_in_kb(path, df, index, file):
#     for root, dirs, files in os.walk(path):
#         if file.endswith('.pdf'):
#             valid_file = check_pdf_file(path + '/' + file)
#             if (valid_file):
#                 df.at[index, 'Integridade'] = 'ok'
#                 print (df.at[index, 'id'] + " - OK")
#             else:
#                 df.at[index, 'Integridade'] = 'no a pdf file'
#                 print (df.at[index, 'id'] + " - BAD PDF")
#                 df.to_csv('dados/TODOS.csv', index = False)
#                 continue
                        
#         file_obj = Path(path + '/' + file)
#         size = file_obj.stat().st_size

#         size_kb = float(size) / 1000  # kB
#         print (df.at[index, 'id'] + " - " + str(size_kb))
#         df.at[index, 'Size'] = size_kb
#         df.to_csv('dados/TODOS.csv', index = False)

#         print('\n\n')


# def get_real_and_zipped_size_in_kb(path, df, index, file):
#     try:
#         zfile = zipfile.ZipFile(path + '/' + file)
#         zipped_size = os.path.getsize(path + '/' + file)
#     except zipfile.BadZipfile as ex:
#         print (df.at[index, 'id'] + " no a zip file: " + ex)
#         df.at[index, 'Integridade'] = 'no a zip file'
#         continue
#     except:

#     #zip test
#     ret = zfile.testzip()
#     if ret is not None:
#         print (df.at[index, 'id'] + " bad zip file, error: " + ret)
#         df.at[index, 'Integridade'] = 'bad zip file'
#     else:
#         df.at[index, 'Integridade'] = 'ok'

#     real_size = sum([zinfo.file_size for zinfo in zfile.filelist])
#     real_size_kb = float(size) / 1000  # kB
#     zipped_size_kb = float(zipped_size) / 1000  # kB

#     print (df.at[index, 'id'] + " - " + str(zip_kb))
#     df.at[index, 'Size'] = real_size_kb
#     df.at[index, 'Zipped size'] = zipped_size_kb
#     df.to_csv('dados/TODOS.csv', index = False)


# def check_pdf_file(fullfile):
#     with open(fullfile, 'rb') as f:
#         try:
#             pdf = PdfFileReader(f)
#             info = pdf.getDocumentInfo()
#             if info:
#                 return True
#             else:
#                 return False
#         except:
#             return False

In [ ]:
# def remove_corrupted_files():
#     i = 0
#     for index, row in df.iterrows():
#         if (row['Integridade'] != 'ok'):
#             file = 'arquivos/' + row['Edital'] + '/' + row['id'] + '/' + row['Nome do Arquivo']
#             print(row['Edital'] + '/' + row['id'])
#             print(row['Arquivo'])
#             i = i + 1
#             if os.path.exists(file):
#                 os.remove(file)
#                 print("Arquivo Removido")
#             else:
#                 print("The file does not exist")

#             df.at[index, 'Baixado'] = 'Não'
#             df.to_csv('dados/TODOS.csv', index = False)
#             print('\n\n')
    
#     print(i)

In [5]:
# def map_files_in_zips (df, arq_zip):
#     i = 0
#     for index, row in df.iterrows():
#         if (row['Baixado'] == 'Sim') and (row['Extensão do Arquivo'] in ['zip', 'x-zip-compressed']):
#             path = 'arquivos/' + row['Edital'] + '/' + row['id']
# #             print(path);
            
#             i = get_all_files_in_zip(path, df, index, row['id'], arq_zip, i)


# def get_all_files_in_zip(path, df, index, df_row_id, arq_zip, i):
#     for root, dirs, files in os.walk(path):
#         for file in files:
#             if file.endswith('.zip'):
#                 with zipfile.ZipFile(path + '/' + file, 'r') as zipObj:
#                     listOfiles = zipObj.infolist()
# #                     print(listOfiles)
#                     for elem in listOfiles:
#                         row = {}
#                         row['red_id'] = df_row_id
#                         row['nome'] = elem.filename.split("/")[-1]
#                         row['tamanho'] = elem.file_size
#                         row['tamanho_zipado'] = elem.compress_size
#                         row['extensão'] = elem.filename.split(".")[-1]
#                         row['path'] = elem.filename
#                         print(str(i) + ' - ', end="")
#                         print(row)
#                         arq_zip.loc[i] = row
#                         arq_zip.to_csv('dados/arquivos_zip.csv', index = False)
        
#                         i = i + 1
#             else:
#                 print('ERROR: ISNT ZIP')
                
#     return i

In [4]:
# map_files_in_zips (df, arq_zip)

In [122]:
# pd.set_option("display.max_rows", None, "display.max_columns", None)
    
# for index, row in arq_zip.iterrows():
#     if (row['extensão'] == 'DS'):
#         print(index)
#         print(row['extensão'])

328
0360P20042_VONTADE_DE_SABER_HISTORIA_V7/
334
0360P20042_VONTADE_DE_SABER_HISTORIA_V8/
429
0379P20062_AUDIOVISUAIS_POR_TODA_PARTE_V9/
464
0386P20022_MATEMATICA_REALIDADE_E_TECNOLOGIA_V9/
